describe('My First Test', () => {
  beforeEach(() => cy.visit('/'))
  it('Does not do much!', () => {
    cy.get('ul.pokemons li.pokemons__item')
      .should('have.length', 784)
      .get('input[placeholder="Enter pokemon name..."]')
      .type('saur')
      .get('ul.pokemons li.pokemons__item')
      .should('have.length', 3)
      .get('input[placeholder="Enter pokemon name..."]')
      .type('{selectall}{backspace}zzzzzzz')
      .get('ul.pokemons li.pokemons__item')
      .should('have.length', 0)
  })
})
